name: Clean GitHub Pages History

on:
  push:
    branches:
      - main  # Вы можете указать вашу основную ветку, если она отличается

jobs:
  clean-gh-pages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Remove GitHub Pages history
      run: |
        # Удаление истории развертываний на GitHub Pages
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # Удаление всех файлов и директорий в gh-pages
        rm -rf public/*

        # Добавление изменений в индекс
        git add -A
        git commit -m "Cleanup GitHub Pages history"
        git push origin main  # Пушим изменения в основную ветку
